version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/aws-devops-pgp/
  - source: /pythonappy.service
    destination: /lib/systemd/system/
hooks:
  BeforeInstall:
    - location: /install_deps
      timeout: 300
      runas: root
  AfterInstall:
    - location: /start_ser
      timeout: 300
      runas: root
