version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/aws-devops-pgp/
  - source: /pythonappy.service
    destination: /lib/systemd/system/
hooks:
  BeforeInstall:
    - location: /scripts/install_deps
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/start_ser
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/install-docker-awscli-kubectl-eskctl
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/push-container
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/setup-eks-cluster
      timeout: 300
      runas: root
      
