custombucket = "destinationtxt"
table = "intellipaat"
databasehost = "database-1.czwcytpysaia.us-east-1.rds.amazonaws.com"
duser = "intel"
dpass = "intel123"
s3database = "intellipaat"
kapp = "http://k8s-game2048-ingress-70a6bcc79e-1198646372.us-west-2.elb.amazonaws.com"
