#!/bin/bash

if (eksctl get fargateprofile --cluster Final | grep Game2048)

then
echo Profile exists !

kubectl apply -f /home/ubuntu/aws-devops-pgp/capcustom.yaml

else
echo Creating fargate profile !

eksctl create fargateprofile --cluster Final --region us-west-2 --name Game2048 --namespace game-2048

kubectl apply -f /home/ubuntu/aws-devops-pgp/capcustom.yaml
fi
